package model;

import javax.xml.bind.annotation.*;
import java.util.Date;
//JAX-B TAKE THE ROLE HERE TO BIND AND MAP THIS CLASS TO XML
// NAME THE ROOT ELEMENT OF THIS CLASS AT THE XML GENERATED BY JAX-B
@XmlRootElement(name = "account")
//Every non-static, non-transient field in a JAXB-bound class will be automatically bound to XML, unless annotated by XmlTransient.
@XmlAccessorType(XmlAccessType.FIELD)
public class Account {
	@XmlAttribute //CONSIDER THIS FIELD AS ATTRIBUTE <... id=".." .../>
	private Long id;
	@XmlTransient //CONSIDER THIS FIELD NOT SERIALIZABLE (IGNORE IT IN RESPONSE AND BINDING)
	private Date dateCreation;
	@XmlElement //CONSIDER THIS FIELD AS PARAMETER <solde .../>
	private double solde;
	@XmlElement //CONSIDER THIS FIELD AS PARAMETER <activated .../>
	private boolean activated;

	public Account() {
		super();
	}

	public Account(Long id, Date dateCreation, double solde, boolean activated) {
		super();
		this.id = id;
		this.dateCreation = dateCreation;
		this.solde = solde;
		this.activated = activated;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getDateCreation() {
		return dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public double getSolde() {
		return solde;
	}

	public void setSolde(double solde) {
		this.solde = solde;
	}

	public boolean isActivated() {
		return activated;
	}

	public void setActivated(boolean activated) {
		this.activated = activated;
	}

}
